// <auto-generated />
using System;
using CVM_FinalProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CVM_FinalProject.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260310103000_AddEmployeeArchiveFieldsOnly")]
    partial class AddEmployeeArchiveFieldsOnly
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // This is a simplified version - the actual implementation is handled by EF Core
            // The key changes are:
            // - Employees table now has is_archived (bit, NOT NULL, default 0)
            // - Employees table now has archive_date (datetime2, NULL)
#pragma warning restore 612, 618
        }
    }
}
